### ISSUE TITLE
can't install and run

### ISSUE THREAD

**Issue by scillidan** [szymonkaliski/cartographist#1]
When I install, it tell me:
```cmd
cartographist λ npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 
or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 
or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 
or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 
or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@3.6.5: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path D:\ketarin\cartographist\node_modules\electron
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! RequestError: unable to verify the first certificate
npm ERR!     at ClientRequest.<anonymous> (D:\ketarin\cartographist\node_modules\got\source\request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:642:26)
npm ERR!     at ClientRequest.emit (node:events:539:35)
npm ERR!     at ClientRequest.origin.emit (D:\ketarin\cartographist\node_modules\@szmarczak\http-timer\source\index.js:37:11)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:442:9)
npm ERR!     at TLSSocket.emit (node:events:527:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:164:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\scillidan\scoop\persist\nodejs\cache\_logs\2022-08-23T13_24_04_056Z-debug-0.log
```

```cmd
cartographist λ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN audit Updating electron to 20.0.3,which is a SemVer major change.
npm WARN audit Updating immer to 9.0.15,which is a SemVer major change.
npm WARN audit Updating webpack to 5.74.0,which is a SemVer major change.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: cartographist@1.0.0
npm WARN Found: webpack@4.44.1
npm WARN node_modules/webpack
npm WARN   peer webpack@">=2" from babel-loader@8.1.0
npm WARN   node_modules/babel-loader
npm WARN     babel-loader@"^8.1.0" from electron-webpack-js@2.4.1
npm WARN     node_modules/electron-webpack-js
npm WARN   15 more (css-loader, electron-webpack, css-loader, file-loader, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^4.42.1" from electron-webpack@2.8.2
npm WARN node_modules/electron-webpack
npm WARN   dev electron-webpack@"^2.8.2" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 
or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 
or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code 1
npm ERR! path D:\ketarin\cartographist\node_modules\electron
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! RequestError: unable to verify the first certificate
npm ERR!     at ClientRequest.<anonymous> (D:\ketarin\cartographist\node_modules\got\source\request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:642:26)
npm ERR!     at ClientRequest.emit (node:events:539:35)
npm ERR!     at ClientRequest.origin.emit (D:\ketarin\cartographist\node_modules\@szmarczak\http-timer\source\index.js:37:11)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:442:9)
npm ERR!     at TLSSocket.emit (node:events:527:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:164:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\scillidan\scoop\persist\nodejs\cache\_logs\2022-08-23T13_24_43_968Z-debug-0.log
```

When I start, it say:
```cmd
cartographist λ npm start

> cartographist@1.0.0 start
> electron-webpack dev

Error: Cannot find module '@babel/preset-react'
Require stack:
- C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\configurators\js.js
- C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\targets\BaseTarget.js
- C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\targets\MainTarget.js
- C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\main.js
- C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\dev\WebpackDevServerManager.js
- C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\dev\dev-runner.js
- C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at addBabelItem (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\configurators\js.ts:44:20)
    at createBabelLoader (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\configurators\js.ts:24:3)
    at MainTarget.configureRules (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\targets\BaseTarget.ts:15:25)
    at MainTarget.configureRules (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\targets\MainTarget.ts:13:11)
    at WebpackConfigurator.configure (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\main.ts:213:12)
    at configure (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\main.ts:376:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\scillidan\\scoop\\persist\\nodejs\\bin\\node_modules\\electron-webpack\\out\\configurators\\js.js',
    'C:\\Users\\scillidan\\scoop\\persist\\nodejs\\bin\\node_modules\\electron-webpack\\out\\targets\\BaseTarget.js',
    'C:\\Users\\scillidan\\scoop\\persist\\nodejs\\bin\\node_modules\\electron-webpack\\out\\targets\\MainTarget.js',
    'C:\\Users\\scillidan\\scoop\\persist\\nodejs\\bin\\node_modules\\electron-webpack\\out\\main.js',
    'C:\\Users\\scillidan\\scoop\\persist\\nodejs\\bin\\node_modules\\electron-webpack\\out\\dev\\WebpackDevServerManager.js',
    'C:\\Users\\scillidan\\scoop\\persist\\nodejs\\bin\\node_modules\\electron-webpack\\out\\dev\\dev-runner.js',
    'C:\\Users\\scillidan\\scoop\\persist\\nodejs\\bin\\node_modules\\electron-webpack\\out\\cli.js'
  ]
}
┏ Renderer -------------------

  Error: Cannot find module '@babel/preset-react'
  Require stack:
  - C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\configurators\js.js
  - C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\targets\BaseTarget.js
  - C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\targets\RendererTarget.js
  - C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\out\main.js
  - C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\webpack.renderer.config.js
  - C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\node_modules\webpack-cli\bin\utils\convert-argv.js
  - C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\node_modules\webpack-dev-server\bin\webpack-dev-server.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:999:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at addBabelItem (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\configurators\js.ts:44:20)
      at createBabelLoader (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\configurators\js.ts:24:3)
      at RendererTarget.configureRules (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\targets\BaseTarget.ts:15:25)
      at RendererTarget.configureRules (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\targets\RendererTarget.ts:20:11)
      at WebpackConfigurator.configure (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\main.ts:213:12)
      at configure (C:\Users\scillidan\scoop\persist\nodejs\bin\node_modules\electron-webpack\src\main.ts:376:10)

┗ ----------------------------
Renderer WDS exited with code 1
```
I try `npm install --save-dev @babel/preset-react`, and seems no effect.

Anywhere, It is an interesting tool, which may be able to have a wonderful use.
Hope you can have more easy time but not laziness, maybe 🤪

**Comment by scillidan** [comment]
It worked with `nodejs v16.14.0`.
This is a lesson I learned using the LTS version🤪
