### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by DavidVollmers** [szymonkaliski/cartographist#5]
This happens when I run `npm start` on windows:

```bash
npm start

> cartographist@1.0.0 start
> electron-webpack dev

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\dev\cartographist\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\dev\cartographist\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\dev\cartographist\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\dev\cartographist\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\dev\cartographist\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\dev\cartographist\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\dev\cartographist\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\dev\cartographist\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\dev\cartographist\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\dev\cartographist\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\dev\cartographist\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
```

**Comment by datengraben** [comment]
You can upgrade webpack and webpack-cli via `npm update webpack webpack-cli` and it works for me with node v22.

**Comment by DavidVollmers** [comment]
Yep that did the trick for me, thanks!
